services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "443:443"
    volumes:
      - ./jenkins.local+1-key.pem:/etc/nginx/certs/jenkins.local+1-key.pem
      - ./jenkins.local+1.pem:/etc/nginx/certs/jenkins.local+1.pem
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - jenkins

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_OPTS=--httpPort=8080

    privileged: true

volumes:
  jenkins_home:
    driver: local
