version: '3.8'

services:
  flask-app1:
    build:
      context: .
    container_name: flask-app1
    ports:
      - "5001:5000"

  flask-app2:
    build:
      context: .
    container_name: flask-app2
    ports:
      - "5002:5000"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask-app1
      - flask-app2
